"""Generate an Excel file summarizing EPBCS dimensions and member counts.

The script reads the JSON output produced by ``epbcs_mcp_basic_auth.py``
which is saved in ``dimensions_output.txt``. It extracts each dimension name
and counts the total number of members (including nested children) under that
dimension. The results are written to ``dimensions.xlsx`` with a single sheet
named ``Dimensions``.

Dependencies: pandas, openpyxl (installed via pip).
"""

import json
import os
from typing import Any, Dict, List

import pandas as pd


def _load_output(path: str) -> Dict[str, Any]:
    """Load the JSON output from the given text file.

    The file may be encoded with UTF‑8, UTF‑16 or contain stray binary
    characters. We read it using UTF‑8 while ignoring decode errors so the
    surrounding text is still captured. The JSON payload is then extracted
    starting from the first ``{`` character.
    """
    # Use errors='ignore' to tolerate non‑UTF‑8 bytes that may appear in the
    # file (e.g., a UTF‑16 BOM). This ensures we can still locate the JSON.
    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        content = f.read()
    # Find the start of the JSON object
    start = content.find("{")
    if start == -1:
        raise ValueError("No JSON object found in output file")
    # Extract the substring from the first opening brace to the matching closing
    # brace. This avoids trailing non‑JSON text that may follow the dump.
    brace_count = 0
    end_index = start
    for i, ch in enumerate(content[start:]):
        if ch == '{':
            brace_count += 1
        elif ch == '}':
            brace_count -= 1
            if brace_count == 0:
                end_index = start + i + 1
                break
    json_str = content[start:end_index]
    try:
        return json.loads(json_str)
    except json.JSONDecodeError:
        # Fallback: the dump may use single quotes (Python representation).
        import ast

        return ast.literal_eval(json_str)


def _count_members(node: Any) -> int:
    """Recursively count all member nodes under a dimension.

    The EPBCS dimension details are nested dictionaries with a ``children``
    list. Each entry in ``children`` may itself contain further ``children``.
    This function counts every node (including the root) as one member.
    """
    if not isinstance(node, dict):
        return 0
    count = 1  # count the current node
    children: List[Dict[str, Any]] = node.get("children", [])
    for child in children:
        count += _count_members(child)
    return count


def main() -> None:
    # Use the JSON file generated by epbcs_mcp_basic_auth.py for reliable parsing
    output_path = "dimensions_output.json"
    if not os.path.exists(output_path):
        raise FileNotFoundError(f"{output_path} not found")

    # Since this file is valid JSON we can load it directly without the custom parser
    with open(output_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    dimensions = data.get("dimensions", [])
    dim_details: Dict[str, Any] = data.get("dimensionDetails", {})

    rows = []
    for dim in dimensions:
        name = dim.get("name")
        if not name:
            continue
        details = dim_details.get(name, {})
        # Count members recursively; if details missing, count is 0
        member_count = _count_members(details) if details else 0
        rows.append({"Dimension": name, "Member Count": member_count})

    df = pd.DataFrame(rows)
    # Write to Excel; sheet name "Dimensions"
    excel_path = "dimensions.xlsx"
    df.to_excel(excel_path, index=False, sheet_name="Dimensions")
    print(f"Excel file written to {excel_path}")


if __name__ == "__main__":
    main()
